### ISSUE TITLE
Chybová stránka

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-bootstrap#19]
Může být takhle?
![image](https://cloud.githubusercontent.com/assets/903531/6288959/281340cc-b91d-11e4-8499-99aea8028ad5.png)

Dodám sem link na html jakmile to někam nasadím.

**Comment by padak** [comment]
divný jsou ty 2 bullety co maj centrovanej text

**Comment by Halama** [comment]
jj to je asi jediny co me tam sere jinak by to asi mohlo bejt pro zacatek ok

**Comment by padak** [comment]
jasan, nechci bejt rejpal - čekám na "go", ale tohle mě ťuklo do očí


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek <http://doodle.com/petrsimecek>

**Comment by Halama** [comment]
tak tady je to videt v HTML http://martin-connection-devel.keboola.com/admin/auth/lofin?xkbcnl
Ten markup se klidne muze menit.

**Comment by Halama** [comment]
asi by bylo dobrý tam šoupnout i link na status.keboola.com
