### ISSUE TITLE
Podpora starých appek

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-bootstrap#2]
Něž vše přesuneme do nové aplikace bylo by super kdybysme v novém UI dokázali nějak slušně vykrelsovat staré aplikace. 
Problém je v tom že jejich součástí je vždy i hlavička. Bude potřeba připravit a nastylovat novej layout.
HTML bude vypadat zhruba takhle https://s3.amazonaws.com/halama/index.html
Přidal jsem tam komentáře kde je popsané s čím se dá hýbat a co už mají pod kontrolou ty aplikace a šahat se na to nedá.

**Comment by JakubMatejka** [comment]
Hotovo. Je teda potřeba zvláštní šablona která nebude mít tu hlavičku a přidá jednu třídu, viz. http://note.io/17yZbpg

**Comment by Halama** [comment]
Právě to nasazuju a všiml jsem si že na ten link v té hlavičce nejde klikat, je jakoby překrytý nějakou vrstvou :) https://kbc-ui-jakub.keboola.com/examples/legacy.php

**Comment by JakubMatejka** [comment]
No jo, jsem s tím byl nějak moc rychle hotovej ;o)
