### ISSUE TITLE
Connection logo v single page layoutu

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-bootstrap#23]
Zobrazuje se nějak divně. Projevuje se v devel režimu nebo to jde vidět přímo v kbc.

![image](https://cloud.githubusercontent.com/assets/903531/8820870/638a2162-3059-11e5-88da-ec52844d1efd.png)

A takhle to vidím tady http://kbc-bootstrap-jakub-devel.keboola.com/examples/single-page.php
![image](https://cloud.githubusercontent.com/assets/903531/8820881/6f770012-3059-11e5-8bc5-656f5bf8e363.png)

**Comment by Halama** [comment]
jde to vidět třeba tady https://connection.keboola.com/admin/account/change-password
Je tam nasazený poslední kbc-bootstrap

**Comment by JakubMatejka** [comment]
Fixnul jsem v layoutu v connection
