### ISSUE TITLE
Move examples and ux-guidelines

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-bootstrap#24]
It is now accesible only here http://kbc-bootstrap-jakub-devel.keboola.com/examples/#templates which is your devel workspace :)

It would be great if it could be on github pages like http://keboola.github.io/angular-kb/#/kb.filter.filesize or https://facebook.github.io/react/index.html

**Comment by ujovlado** [comment]
vznika indigo-ui, examples uz budu tam, zatvaram
