### ISSUE TITLE
nakreslit - Dropdown uživatele

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-bootstrap#3]
Tady https://www.evernote.com/shard/s31/sh/e2b29792-9533-4e0b-a881-078598cefd5f/ddad3049fc78598977657f5cb09817c6/deep/0/Martinuv---Home---Keboola-Connections.png by se hodila asi nějaká šipečka pod kterou by vyjelo menu uživatele. 
Logout, změna hesla, manage apps apodobně. Obdoba současného 
![image](https://cloud.githubusercontent.com/assets/903531/6167932/94d371cc-b2c0-11e4-948c-d9d492b69832.png)

**Comment by odinuv** [comment]
Jo, + takova vec, ktera mi lezi delsi dobu v hlave - nemel by tam byt i token do storage? Ja vim, ze to je token pro storage API, ale davno se nepouziva jen pro storage cally, ale pro kde co, nemel by teda povysit? Ve stavajicim UI si na to osobne nemuzu porad zvyknout, ze token je 'uvnitr' storage

**Comment by Halama** [comment]
jo klidne by ta mohl byt
