### ISSUE TITLE
sidebar dropdown offset

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-bootstrap#38]
![image](https://cloud.githubusercontent.com/assets/903531/23506783/470c3b62-ff4a-11e6-9170-28eec742f028.png)

Same for user dropdown:
![image](https://cloud.githubusercontent.com/assets/903531/23506799/5815e8e0-ff4a-11e6-8701-aa10c01429ae.png)

**Comment by ujovlado** [comment]
akurat vcera som to tiez pozeral a rozmyslal, ze by som dalk ten dropdown dolava  (t.j. button na otvorenie by bol vedla mena a nemuseli by sme riesit tieto prasciny :)

kuknem to ;)

**Comment by Halama** [comment]
super diky. Imho kdyby to spravne fungovalo a bylo to zarovnany tak to nebude vypadat spatne :)
To jak jsi to popsal moc nerozumim jak to myslis...

**Comment by ujovlado** [comment]
dam screenshoty

**Comment by ujovlado** [comment]
Bude fixnute s upgradom na react-14: https://github.com/keboola/kbc-ui/pull/819

![screenshot_2017-04-26_15-57-54](https://cloud.githubusercontent.com/assets/419849/25438334/60c56d88-2a99-11e7-8abc-444f10b9d9f8.png)
![screenshot_2017-04-26_15-57-28](https://cloud.githubusercontent.com/assets/419849/25438333/60c5a0f0-2a99-11e7-9a67-ff5f0957e477.png)

**Comment by Halama** [comment]
paráda, tohle mě tam hrozně sere:)

**Comment by ujovlado** [comment]
Fixed in #43
