### ISSUE TITLE
Loading stav aplikace

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-bootstrap#8]
![image](https://cloud.githubusercontent.com/assets/903531/6209397/d3668250-b5c5-11e4-8e79-b1f76638318b.png)

Mohlo by být třeba nějak vycentrované jako u Slacku

**Comment by JakubMatejka** [comment]
nevíš jaký to má markup? Snažím se to někde odchytit a nedaří se mi ;o)

**Comment by Halama** [comment]
Je to tohle https://github.com/keboola/connection/blob/master/application/modules/admin/views/scripts/projects/main-app.phtml#L17

Může se nahradit jakýmkoliv jiným markupem

**Comment by Halama** [comment]
Zobrazuje se to předtím než to celý replacne ta SPA aplikace

**Comment by JakubMatejka** [comment]
https://kbc-ui-jakub.keboola.com/examples/loading.php
Může být? Bylo by třeba ten markup upravit takto:
```html
<div class="kbc-main-loader">
    <i class="fa fa-spin fa-spinner"></i>
    <span>Loading ...</span>
</div>
```

**Comment by Halama** [comment]
jo to vypadá super. dík
